// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR0hwvx-At9VnFrKsNRHtkP6OhuqOcMEs',
    appId: '1:496253345149:web:76a54599d07f9fd6ea0014',
    messagingSenderId: '496253345149',
    projectId: 'chatapp-b97cd',
    authDomain: 'chatapp-b97cd.firebaseapp.com',
    storageBucket: 'chatapp-b97cd.appspot.com',
    measurementId: 'G-XH4CQ777ZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDCmLgvD4jdCPrWv7B3h_PR-j39DDTKb0',
    appId: '1:496253345149:android:6065d54e8da42428ea0014',
    messagingSenderId: '496253345149',
    projectId: 'chatapp-b97cd',
    storageBucket: 'chatapp-b97cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZHCeGU8PsqDEOq1W4XFs2DQ6Osym7Lz8',
    appId: '1:496253345149:ios:e27c9a7311addf21ea0014',
    messagingSenderId: '496253345149',
    projectId: 'chatapp-b97cd',
    storageBucket: 'chatapp-b97cd.appspot.com',
    androidClientId: '496253345149-0orbjf16i59ded7au4fuffsneidn6n49.apps.googleusercontent.com',
    iosClientId: '496253345149-vrjmv3kf6msmtbie2uc2dni2or9344c7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZHCeGU8PsqDEOq1W4XFs2DQ6Osym7Lz8',
    appId: '1:496253345149:ios:1d567f0c08f15f98ea0014',
    messagingSenderId: '496253345149',
    projectId: 'chatapp-b97cd',
    storageBucket: 'chatapp-b97cd.appspot.com',
    androidClientId: '496253345149-0orbjf16i59ded7au4fuffsneidn6n49.apps.googleusercontent.com',
    iosClientId: '496253345149-7lau3qf1mjf69guffc8245n0i3vbn052.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
